#override defaults for dev
version: "3.7"

services:
  app_server:
    volumes:
      - ~/.npm:/.npm
    environment:
      CONTAINER_UID: __USER_ID__
      APPLICATION_UID: __USER_ID__
      APPLICATION_GID: __GROUP_ID__
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8005:8005"
      - "127.0.0.1:9998:9998"
      - "127.0.0.1:9999:9999"

  app_mysql:
    ports:
      - "127.0.0.1:4406:3306"
    volumes:
      - mysql-data:/mysql-data

  adminer:
    ports:
      - "127.0.0.1:8001:8080"

  mailhog:
    ports:
      - "127.0.0.1:8002:8025"

  elasticsearch:
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"

volumes:
    mysql-data:
